# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: contracts changed
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 17 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: ${{ matrix.java }}

      - name: Build with Maven
        run: mvn test package jacoco:report

      - name: Run Specmatic Insights Github Build Reporter
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_API_ACCESS_TOKEN }}
        run: |
          api_url="https://api.github.com/repos/${{ github.repository }}/actions/workflows"
          workflow_name="${{ github.workflow }}"
          response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" $api_url)
          workflow_id=$(echo "$response" | jq -r --arg workflow_name "$workflow_name" '.workflows[] | select(.name == $workflow_name) | .id')
          echo "Workflow ID: $workflow_id" # Debug print
          docker run \
            -v ${{ github.workspace }}:/workspace \
            znsio/specmatic-insights-github-build-reporter:latest \
              --specmatic-insights-host https://insights.specmatic.in \
              --specmatic-reports-dir /workspace/build/reports/specmatic \
              --org-id ${{ secrets.SPECMATIC_ORG_ID }} \
              --branch-ref ${{ github.ref }} \
              --branch-name ${{ github.ref_name }} \
              --build-definition-id "$workflow_id" \
              --build-id ${{ github.run_id }} \
              --repo-name ${{ github.event.repository.name }} \
              --repo-id ${{ github.repository_id }} \
              --repo-url ${{ github.event.repository.html_url }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco coverage report
          path: /home/runner/work/specmatic-order-api/specmatic-order-api/target/site/jacoco

      - name: Upload HTML Test Report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.java }}-html-report
          path: build/reports/specmatic/html
